version: '3'

includes:
  platform:
    taskfile: taskfile.{{OS}}.yml
    optional: true
    flatten: true

vars:
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  LDFLAGS: >-
    -s -w
    -X main.version={{.VERSION}}

tasks:
  build:
    desc: Cross-compile for multiple platforms
    cmds:
      - mkdir -p dist
      - for:
          - { GOOS: darwin, GOARCH: amd64, SUFFIX: darwin-amd64 }
          - { GOOS: darwin, GOARCH: arm64, SUFFIX: darwin-arm64 }
          - { GOOS: linux, GOARCH: amd64, SUFFIX: linux-amd64 }
          - { GOOS: linux, GOARCH: arm64, SUFFIX: linux-arm64 }
          - { GOOS: windows, GOARCH: amd64, SUFFIX: windows-amd64.exe }
        cmd: >-
          docker run --rm
          -v "$PWD":/app -w /app
          -e CGO_ENABLED=0 -e GOOS={{.ITEM.GOOS}} -e GOARCH={{.ITEM.GOARCH}}
          golang:1.26-alpine
          go build -ldflags="{{.LDFLAGS}}"
          -o dist/hourgit-{{.ITEM.SUFFIX}}
          ./cmd/hourgit

  test:
    desc: Run all tests
    cmd: docker run --rm -v "$PWD":/app -w /app golang:1.26-alpine go test -v -count=1 ./...

  lint:
    desc: Run golangci-lint (format + static analysis)
    cmd: docker run --rm -v "$PWD":/app -w /app golangci/golangci-lint:v2.10.1-alpine golangci-lint run ./...
